using System;
using Debugger = Debugland.Debugger;

namespace Saga.Model
{
    public class CardList
    {
        public List<OccupationCard>? Cards{ get; set; }
        public List<OccupationCard> GetOccupationCards()
        {
            Debugger.MethodInitiated("GetOccupationCards");
            Cards =
            [
                new(1,'A', "Peddler",0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(2, 'B', "Patron", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(3, 'A', "Furrier", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(4, 'c', "Hunter", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(5, 'A', "Chief", 7, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(6, 'B', "Stone Carver", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(7, 'A', "Miller", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(8, 'a', "Craft Leader", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(9, 'A', "Ore Boatman", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(10, 'A', "Milker", 7, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(11, 'c', "Trident Hunter", 1, CardAbilityType.Immediate, EnumOccuCard.starting_Occupation_Card),
                new(12, 'A', "Helmsman", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(13, 'B', "Archer", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(14, 'C', "Ship Owner", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(15, 'C', "Cottager", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(16, 'C', "Captain", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(17, 'A', "Orient Shipper", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(18, 'A', "Fighter", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(19, 'C', "Host", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(20, 'A', "Builder", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(21, 'b', "Collector", 1, CardAbilityType.Immediate, EnumOccuCard.starting_Occupation_Card),
                new(22, 'A', "Miner", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(23, 'A', "Custodian", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(24, 'A', "Whaling Equipper", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(25, 'B', "Meat Trader", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(26, 'c', "Meat Inspector", 0, CardAbilityType.Immediate, EnumOccuCard.starting_Occupation_Card),
                new(27, 'A', "Fisherman", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(28, 'B', "Locksmith", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(29, 'B', "Meat Preserver", 3, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(30, 'B', "Silk Merchant", 3, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(31, 'C', "Storeman", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(32, 'A', "Weapons Supplier", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(33, 'A', "Sheep Shearer", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(34, 'A', "Sheperd", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(35, 'A', "Cattle Breeder", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(36, 'A', "Ship's Cook", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(37, 'A', "Foreign Trader", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(38, 'A', "Peacemaker", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(39, 'C', "Modifier", 2, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(40, 'B', "Master Joiner", 3, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(41, 'a', "Slowpoke", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(42, 'b', "Steward", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(43, 'A', "Fruit Picker", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(44, 'B', "Master Tailor", 1, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(45, 'C', "Pirate", -1, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(46, 'B', "Ship Architect", 1, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(47, 'a', "Tanner", 2, CardAbilityType.Anytime, EnumOccuCard.starting_Occupation_Card),
                new(48, 'A', "Farmer", 3, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(49, 'C', "Plower", 3, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(50, 'A', "Rune Engraver", 2, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(51, 'B', "Master Mason", 1, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(52, 'a', "Tutor", 0, CardAbilityType.Anytime, EnumOccuCard.starting_Occupation_Card),
                new(53, 'b', "FarmShop Owner", 1, CardAbilityType.Anytime, EnumOccuCard.starting_Occupation_Card),
                new(54, 'A', "Tradesman", 3, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(55, 'C', "Treasurer", 2, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(56, 'A', "Arms Dealer", 1, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(57, 'b', "Bean Farmer", 1, CardAbilityType.Anytime, EnumOccuCard.starting_Occupation_Card),
                new(58, 'A', "Linseed Oil Presser", 3, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(59, 'A', "Linen Weaver", 0, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(60, 'C', "Inspector", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(61, 'C', "Wharf Owner", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(62, 'b', "Fine Blacksmith", 3, CardAbilityType.Immediate, EnumOccuCard.starting_Occupation_Card),
                new(63, 'C', "Hornturner", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(64, 'A', "Ship Builder", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(65, 'A', "Dragon-slayer", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(66, 'A', "Field Farmer", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(67, 'C', "Private Chef", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(68, 'A', "Supplier of Weapons", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(69, 'c', "Equipment Supplier", 1, CardAbilityType.Immediate, EnumOccuCard.starting_Occupation_Card),
                new(70, 'B', "Courier", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(71, 'C', "Inkeeper", -1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(72, 'B', "Earl", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(73, 'C', "MetalSmith", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(74, 'A', "Cowherd", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(75, 'C', "Bone Collector", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(76, 'A', "Homecomer", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(77, 'A', "Follower", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(78, 'B', "Traveling Merchant", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(79, 'A', "Breeder", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(80, 'B', "Shepherd Boy", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(81, 'C', "Quarter-master", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(82, 'B', "Longship Builder", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(83, 'A', "Wholesaler", 1, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(84, 'B', "Harbor Guard", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(85, 'C', "Hornblower", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(86, 'A', "Hide Buyer", 3, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(87, 'A', "Preacher", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(88, 'C', "Clerk", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(89, 'a', "Catapulter", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(90, 'C', "Sword Fighter", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(91, 'c', "Latecomer", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(92, 'C', "Sympathic Soul", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(93, 'C', "Helper in Time of Need", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(94, 'A', "Spice Merchant", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(95, 'A', "Wanderer", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(96, 'A', "Meat Merchant", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(97, 'B', "Pea Counter", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(98, 'A', "Nobelman", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(99, 'A', "Perceptor", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(100, 'b', "Undertaker", -1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(101, 'B', "Judge", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(102, 'B', "Fur Merchant", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(103, 'C', "Forest Blacksmith", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(104, 'b', "Dishartened Warrior", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(105, 'B', "Knarr Builder", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(106, 'B', "Warmonger", -1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(107, 'B', "Adventurer", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(108, 'c', "Ironsmith", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(109, 'B', "Master Count", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(110, 'C', "Birka Settler", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(111, 'C', "Artist", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(112, 'b', "Barkeeper", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(113, 'a', "Apprentice Craftsman", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(114, 'C', "Silk Stitcher", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(115, 'b', "Princess", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(116, 'c', "Master Bricklayer", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(117, 'A', "Shipowner", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(118, 'c', "Messenger", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(119, 'b', "Milkman", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(120, 'b', "Middelman", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(121, 'B', "Carpenter", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(122, 'A', "Mountain Guard", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(123, 'C', "Oil Seller", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(124, 'B', "Laborer", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(125, 'c', "Scribe", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(126, 'A', "Trapper", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(127, 'b', "Angler", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(128, 'A', "Digger", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(129, 'b', "Meat Curer", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(130, 'C', "Snare Specialist", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(131, 'c', "Bait Layer", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(132, 'b', "Berserker", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(133, 'B', "Lance Bearer", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(134, 'A', "Drunkard", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(135, 'A', "Lone Wolf", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(136, 'c', "Raider", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(137, 'a', "Melee Fighter", 3, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(138, 'c', "Robber", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(139, 'C', "Loot Hunter", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(140, 'A', "Blubber Cook", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(141, 'c', "Ivory Sculptor", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(142, 'B', "Whale Catcher", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(143, 'B', "Antlers Seller", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(144, 'B', "Deerstalker", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(145, 'A', "Forester", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(146, 'C', "Sledger", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(147, 'A', "Steersmen", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(148, 'C', "Spice Trader", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(149, 'A', "Priest", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(150, 'c', "Meat Buyer", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(151, 'c', "Thing Spokesman", 3, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(152, 'A', "Merchant", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(153, 'a', "Proficient Hunter", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(154, 'a', "Woodcutter", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(155, 'b', "Cooper", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(156, 'B', "Stone Crusher", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(157, 'C', "Skinner", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(158, 'A', "Barbarian", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(159, 'B', "Festive Hunter", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(160, 'a', "Sober Man", 2, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(161, 'B', "Whaling Assistant", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(162, 'C', "Flax Farmer", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(163, 'a', "Farmhand", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(164, 'A', "Armed Fighter", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(165, 'A', "Village Leader", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(166, 'B', "Weapons Warden", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(167, 'B', "Taster", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(168, 'C', "Earl of Lade", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(169, 'C', "Sower", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(170, 'a', "Refuge Helper", 0, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(171, 'A', "Flax Baker", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(172, 'C', "Fish Cook", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(173, 'B', "Punchcutter", 1, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(174, 'a', "Bosporus Traveller", 1, CardAbilityType.Each_Time, EnumOccuCard.starting_Occupation_Card),
                new(175, 'B', "Codliver Oil Presser", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(176, 'B', "Etiquette", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(177, 'B', "Maid", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(178, 'B', "Boat Builder", 0, CardAbilityType.As_Soon_As, EnumOccuCard.Occupation_Card),
                new(179, 'B', "Cutter Operator", 2, CardAbilityType.As_Soon_As, EnumOccuCard.Occupation_Card),
                new(180, 'C', "Beach Raider", -2, CardAbilityType.As_Soon_As, EnumOccuCard.Occupation_Card),
                new(181, 'C', "Sail Patcher", 1, CardAbilityType.As_Soon_As, EnumOccuCard.Occupation_Card),
                new(182, 'C', "Herb Gardener", 1, CardAbilityType.As_Soon_As, EnumOccuCard.Occupation_Card),
                new(183, 'C', "Grain Delivery-man", 2, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(184, 'C', "Sponsor", 0, CardAbilityType.Immediate, EnumOccuCard.Occupation_Card),
                new(185, 'B', "Dorestad Traveller", 2, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(186, 'A', "Pea Flour Baker", 3, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(187, 'B', "Chronicler", 2, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(188, 'C', "Mineworker", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
                new(189, 'B', "Seafarer", 1, CardAbilityType.Anytime, EnumOccuCard.Occupation_Card),
                new(190, 'B', "Bosporus Merchant", 0, CardAbilityType.Each_Time, EnumOccuCard.Occupation_Card),
            ];
            Debugger.MethodTerminated("GetOccupationCards");
            return Cards;
        }
        
    }
}
